apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-catalog
  labels:
    app: netflix-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-catalog
  template:
    metadata:
        labels:
          app: netflix-catalog
    spec:
      containers:
      - name: server
        image: talorlik/netflix-movie-catalog-dev:v1.0.15
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/"
            port: 8081
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/status"
            port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-catalog-service
spec:
  selector:
    app: netflix-catalog
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
