apiVersion: v1
kind: Secret
metadata:
  name: influx-admin-credentials
type: Opaque
data:
  INFLUX_ADMIN_USER: YWRtaW4=                # echo -n 'your-username' | base64
  INFLUX_ADMIN_PASSWORD: UEBzc3dvcmQxMjM=    # echo -n 'your-password' | base64
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
        labels:
          app: influx
    spec:
      containers:
      - name: server
        image: influxdb:1.8.10
        env:
          - name: INFLUXDB_HTTP_AUTH_ENABLED
            value: 'true'
          - name: INFLUX_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: influx-admin-credentials
                key: INFLUX_ADMIN_USER
          - name: INFLUX_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: influx-admin-credentials
                key: INFLUX_ADMIN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: influx-service
spec:
  selector:
    app: influx
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
