apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: YWRtaW4=                # echo -n 'your-username' | base64
  GF_SECURITY_ADMIN_PASSWORD: UEBzc3dvcmQxMjM=    # echo -n 'your-password' | base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
          {
            "version": 2,
            "name": "Redis",
            "type": "redis-datasource",
            "url": "redis://redis-service:6379",
            "isDefault": true
          }
        ]
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
        labels:
          app: grafana
    spec:
      containers:
      - name: server
        image: grafana/grafana:9.5.20-ubuntu
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: 'true'
          - name: GF_INSTALL_PLUGINS
            value: redis-datasource
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: grafana-admin-credentials
                key: GF_SECURITY_ADMIN_USER
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-admin-credentials
                key: GF_SECURITY_ADMIN_PASSWORD
        volumeMounts:
          - name: grafana-config
            mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
